### ISSUE TITLE
Add TLS to APICheck

### ISSUE THREAD

**Issue by codygreen** [codygreen/lab-framework-demo#123]
Extend the APICheck component to include TLS so we can check encrypted URLs.

Ensure this works with both URLs and components.

**Comment by aknot242** [comment]
Might be able to use `NODE_TLS_REJECT_UNAUTHORIZED` env var to bypass certificate verification, but if this works it would be a global setting. 

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by aknot242** [comment]
Closed via #130
