### ISSUE TITLE
Duplicate header ids result in anchors not working 

### ISSUE THREAD

**Issue by aknot242** [codygreen/lab-framework-demo#137]
Duplicate headers will not link. Need to find a durable way to add unique identifiers that aren't random every lab instance or refresh.

FYI, this plugin would be ideal, but the default unique id setting does not seem to work for me. Might be an MDXJS v2 issue: https://github.com/sindresorhus/remark-custom-header-id

**Comment by aknot242** [comment]
@codygreen reopening, not resolved. Anchors having the same title are duplicates, so will not link correctly:

![image](https://github.com/user-attachments/assets/2274ff9c-16bf-4647-b9bb-e8a8acc45f85)

In the above page, each duplicate link results in `#example`, so there is no uniqueness. As a result, the browser doesn't know which one to scroll to.

**Comment by codygreen** [comment]
fixed in #152
