### ISSUE TITLE
Color the tile of the API* check components

### ISSUE THREAD

**Issue by aknot242** [codygreen/lab-framework-demo#142]
To make the results more obvious, color successful checks as green; unsuccessful as red. Here's the current experience.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/54a881ca-f7fe-43a2-9bff-88d0f0093b93">

**Comment by codygreen** [comment]
Thank you for confirming, I thought it might be a caching issue for me. 

They are colored, but it's getting overwritten somewhere.  I had an issue opened over the weekend on this problem.  However, when I add a <p> or <span> with the same color styling the Error and MSG boxes used the correct color again, without any code modification on their component.   

It's a CSS issue, I'm just not sure where.
