### ISSUE TITLE
Expanding Large Images Doesn't Show X (close) Icon

### ISSUE THREAD

**Issue by jswongF5** [codygreen/lab-framework-demo#162]
There is an `x` near the top right of the expanded image when you click on it.
![image](https://github.com/user-attachments/assets/34894441-d191-4845-9f4b-32c758a5e77a)

If there is a bigger image, that `x` appears to go off the screen.
![image](https://github.com/user-attachments/assets/7612df07-e2dc-42d0-b1b7-60ee617c99a0)

Workaround: Press your `esc` button.

**Comment by aknot242** [comment]
@jswongF5 - I viewed the image you are showing above, and I see the "x" still. Can we look at this?

**Comment by jswongF5** [comment]
Ok, I see what's going on. This issue isn't that big as issue then.

When I shrink my web browser's window, it will eventually show up. I think it is a corner case when I expand my the width, it goes away. Below is a screenshot just as the 'x' goes away.

<img width="1701" alt="image" src="https://github.com/user-attachments/assets/f4a75b41-c0fe-498e-ac09-d75ea28a8903">

**Comment by aknot242** [comment]
@jswongF5  with the updates to the image viewer component over the last couple days, is this now better?

**Comment by jswongF5** [comment]
Yup! This is no longer an issue.

![image](https://github.com/user-attachments/assets/edaa8816-aae4-40a4-86cb-09372abdf473)
