### ISSUE TITLE
Containerize Framework and dependent services

### ISSUE THREAD

**Issue by aknot242** [codygreen/lab-framework-demo#20]
Need to set up a build system to build the framework (and nextjs server) into a container published in ghcr.

**Comment by codygreen** [comment]
look at options to use DockerCompose to deploy Next JS and Redis containers or combine Next JS and Redis in a single container.  Evaluate pros/cons.

**Comment by aknot242** [comment]
Still need to set up GitHub actions to build our production lab-framework and redis containers

**Comment by aknot242** [comment]
Complete.
