### ISSUE TITLE
Inline code blocks not supported

### ISSUE THREAD

**Issue by aknot242** [codygreen/lab-framework-demo#29]
Currently, the usage of the ` will not work with the framework. The output from the compiler doesn't distinguish the two, so the CodeBlock component doesn't know how to render them differently. It assumes all of them are fenced code blocks. Requires additional research to fix. 

Temporarily, favor bolded lines instead of inline code syntax.

If you attempt to use inline code blocks, you may see the following error:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

In HTML, <div> cannot be a descendant of <p>.
This will cause a hydration error.


...
  <li>
    <p>
    ^^^
      <code>
        <CodeBlock>
          <div>
          ^^^^^
```

**Comment by aknot242** [comment]
might try the pre and code components shown here to see if there is a better approach: https://github.com/hashicorp/next-mdx-remote/issues/356#issuecomment-2082036861

**Comment by aknot242** [comment]
Also worth looking at https://github.com/hashicorp/next-mdx-remote/issues/244

**Comment by Henryyy-Hung** [comment]
> @Henryyy-Hung thank you very much for your suggestion. It works great!

you are welcome
