### ISSUE TITLE
Stub Status allow list needs to include Docker Network

### ISSUE THREAD

**Issue by codygreen** [codygreen/lab-framework-demo#81]
We need to do 2 things:

1. Verify the docker network in UDF falls within: `172.18.0.0/8`
2. Update the screenshot in the lab guide to include the updated allow list:

 ```nginx
  location /nginx_status {
      stub_status;
      allow 10.0.0.0/8;
      allow 172.18.0.0/16;
      allow 127.0.0.1;
      deny all;
  }
```

**Comment by aknot242** [comment]
I have this queued up - just waiting for N1SC to be back up to take the screenshot.

**Comment by aknot242** [comment]
Closing. Screenshots will be taken with the final stretch of lab development.
