### ISSUE TITLE
Horizontal scrolling required when viewing mdx on smaller viewport

### ISSUE THREAD

**Issue by aknot242** [codygreen/lab-framework-demo#98]
May be that the images + the whitespace around them? Either way, the view needs to shrink/grow dynamically based on window size. Text content should wrap. 

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/329e29b3-fb11-4770-8a18-e29b5b549ca8">

**Comment by codygreen** [comment]
fixed in #106 
added toc hide and no overflow of text on right side
